spring:
  ai:
    openai:
      api-key: ollama
      base-url: http://127.0.0.1:11434/v1
      connect-timeout: 60s
      read-timeout: 120s
      chat:
        model: qwen3:8b
  application:
    name: atlas-bank
  datasource:
    url: jdbc:h2:mem:atlasbank
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/atlas-bank

logging:
  level:
    org.springframework.ai: DEBUG
    org.springframework.web.client.RestClient: DEBUG
    org.springframework.http.client: DEBUG