spring:
  ai:
    bedrock:
      aws:
        region: us-east-1
        profile:
          name: twdc-bedrock-central
      converse:
        chat:
          options:
            model: us.anthropic.claude-sonnet-4-20250514-v1:0
  application:
    name: atlas-bank
  datasource:
    url: jdbc:h2:mem:atlasbank
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/atlas-bank

logging:
  level:
    org.springframework.ai: DEBUG
    org.springframework.web.client.RestClient: DEBUG
    org.springframework.http.client: DEBUG